apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-self-signed-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-trust-anchor
  namespace: cert-manager
spec:
  commonName: root.linkerd.cluster.local
  isCA: true
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: linkerd-identity-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-identity-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: linkerd-identity-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-webhook-trust-anchor
  namespace: cert-manager
spec:
  commonName: webhook.linkerd.cluster.local
  isCA: true
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: linkerd-webhook-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-webhook-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: linkerd-webhook-trust-anchor